### ISSUE TITLE
Download of MyScratch table fails with http error

### ISSUE THREAD

**Issue by thakar** [sciserver/CasJobs#58]
When I click on the Download link for a MyScratch table on the Output page, I get the following error:
502 - Web server received an invalid response while acting as a gateway or proxy server.
A regular MyDB table download works fine. This is on a macbook air from an outside connection.

**Comment by dmedv** [comment]
Your file is probably too large. Can you try with smaller files. This is a sciserver04 configuration issue, not CasJobs itself.

**Comment by thakar** [comment]
Yes, a small file works fine, but the error comes up almost instantaneously
for a large file ( ~ 1 GB) so it's not like it's timing out or something.

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Any technology distinguishable from magic is insufficiently advanced.
[Anon.]

**Comment by dmedv** [comment]
It is not timing out, but IIS is probably configured to block all content larger than certain size. Let me know if you would like this increased for sciserver04, and the new maximum content size.

**Comment by thakar** [comment]
What's the setting on the production servers?  We don't want to run into
this once we go live.  What's the maximum value?

      Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Any technology distinguishable from magic is insufficiently advanced.
[Anon.]

**Comment by dmedv** [comment]
I don't know... I don't have access to production servers.

**Comment by thakar** [comment]
Following a f2f with Mitya just now, we decided that he will try to bump up
the limit on sciserver04 to 10 GB for starters.  We don't yet know exactly
which limit needs to be tweaked.  Also, whatever we do on sciserver04 does
not apply to the production (windows) servers once we deploy this there.
We may well run into other issues there e.g. the load balancer timeout.

In the future the CJ downloads will be handled by FTP links, as we
discussed a few weeks ago.  One of main goals of the MyScratch feature is
to let users download large (>> few GB) files on their own without our
intervention, so we definitely need to be able to support this in the
production environment at some point.

        Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
I believe I have no prejudices whatsoever. All I need to know is that a
man is a member of the human race.  That's bad enough for me. [M.Twain]

**Comment by dmedv** [comment]
After a few unsuccessful attempts to reconfigure the proxy, I have simply moved the CasJobs output folder to \\sciserver04\data\data1\www\cjoutput and exposed it directly through sciserver04 IIS, thus bypassing the proxy. Seems to have solved the problem.
