### ISSUE TITLE
After linking CasJobs account, CasJobs does not auto-login

### ISSUE THREAD

**Issue by raddick** [sciserver/CasJobs#61]
I used the existing user legacy_090 to create a new portal account. After I created the portal account, the portal correctly showed me that I am logged in as legacy_090. Then I clicked on CasJobs in the right-hand set of links. CasJobs opens in a new window, but I am not logged in as legacy_090. I have to click the "Login" button in the top right. After clicking this button, I'm automatically logged in.

The behavior the user expects is that after creating an account and going to CasJobs, they should already be logged in to CasJobs using the account they just created/linked.

**Comment by thakar** [comment]
Same as #55, I think.
