### ISSUE TITLE
Fail to download table in MyDB to SCiDrive.

### ISSUE THREAD

**Issue by jkim485** [sciserver/CasJobs#65]
Got the following error message:
Object reference not set to an instance of an object. at edu.jhu.Cas.Service.OutputThread.CreateSciDriveContainer(String path, String token) at edu.jhu.Cas.Service.OutputThread.ProcessJob(Job job)

**Comment by dmedv** [comment]
Fixed. SciDrive URL was missing from the config file.

**Comment by jkim485** [comment]
Can I test it?

**Comment by dmedv** [comment]
Yes, of course...

**Comment by jkim485** [comment]
tested and the fix confirmed.
